#!/usr/bin/env node
parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"0Kt0":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const t=e(require("fs")),r=e(require("jsonfile")),s=e(require("os")),i=e(require("path"));exports.dir=i.default.join(s.default.homedir(),".chaos"),exports.path=i.default.join(exports.dir,"config.json"),exports.init=(()=>{t.default.existsSync(exports.dir)||t.default.mkdirSync(exports.dir),exports.save({})}),exports.exists=(()=>t.default.existsSync(exports.dir)&&t.default.existsSync(exports.path)),exports.save=(e=>r.default.writeFileSync(exports.path,e)),exports.load=(()=>r.default.readFileSync(exports.path));
},{}],"8oQ/":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var s in e)Object.hasOwnProperty.call(e,s)&&(t[s]=e[s]);return t.default=e,t},t=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const s=e(require("inquirer")),a=t(require("web3")),r=new a.default,i={ADDRESS:"0xcdf45df24d878dd7e564a72802ba23031acfac07",DEVICES:!1,ETHEREUM:"https://mainnet.infura.io/v3/ab05225130e846b28dc1bb71d6d96f09",IPFS:"https://ipfs.infura.io:5001",MNEMONIC:"journey nice rather ball theme used uncover gate pond rifle between state"},n=new RegExp(/(?:^|\s)((https?:\/\/)?(?:localhost|[\w-]+(?:\.[\w-]+)+)(:\d+)?(\/\S*)?)/);exports.questions={ipfs:{name:"ipfs",type:"input",message:"IPFS gateway: ",default:i.IPFS,validate:async e=>!!e.match(n)||"Invalid URL"},ethereum:{name:"ethereum",type:"input",message:"Ethereum gateway: ",default:i.ETHEREUM,validate:async e=>!!e.match(n)||"Invalid URL"},mnemonic:{name:"mnemonic",type:"input",message:"Mnemonic: ",default:i.MNEMONIC},address:{name:"address",type:"input",message:"Contract address: ",default:i.ADDRESS,validate:async e=>!!r.isAddress(e)||"Invalid address"},devices:{name:"devices",type:"confirm",message:"Enable devices: ",default:i.DEVICES}},exports.prompt={configure:async()=>{const e=await s.prompt(exports.questions.ipfs),t=await s.prompt(exports.questions.ethereum),a=await s.prompt(exports.questions.mnemonic),r=await s.prompt(exports.questions.address),i=await s.prompt(exports.questions.devices);return Object.assign({},e,t,a,r,i)}},exports.default=exports.prompt;
},{}],"OE6f":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var s={};if(null!=e)for(var i in e)Object.hasOwnProperty.call(e,i)&&(s[i]=e[i]);return s.default=e,s},s=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const i=e(require("../../lib/config")),t=s(require("../../ui/inquirer")),r=s(require("yargs")),o=()=>r.default.option("ipfs",{describe:"Set IPFS gateway address",type:"string"}).option("ethereum",{describe:"Set ethereum gateway address",type:"string"}).option("address",{describe:"Set contract address",type:"string"}).option("mnemonic",{describe:"Set ethereum account mnemonic",type:"string"}).option("devices",{describe:"Enable chaos machine devices",type:"boolean"}).help().version(!1),n=async e=>{try{if(i.exists()||i.init(),e.ipfs){const s=i.load();s.ipfs=e.ipfs,i.save(s)}else if(e.ethereum){const s=i.load();s.ethereum=e.ethereum,i.save(s)}else if(e.address){const s=i.load();s.address=e.address,i.save(s)}else if(e.mnemonic){const s=i.load();s.mnemonic=e.mnemonic,i.save(s)}else if(void 0!==e.devices){const s=i.load();s.devices=e.devices,i.save(s)}else{const e=await t.default.configure();i.save(e)}}catch(e){console.log("[error] "+e.message)}};exports.config={command:"config",desc:"Configure the Chaos Machine",builder:o,handler:n};
},{"../../lib/config":"0Kt0","../../ui/inquirer":"8oQ/"}],"jTSK":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var o={};if(null!=e)for(var n in e)Object.hasOwnProperty.call(e,n)&&(o[n]=e[n]);return o.default=e,o},o=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const n=e(require("../../lib/config")),r=o(require("asciiart-logo")),a=require("@chaosmachine/chaos.js"),i=o(require("yargs")),t=()=>i.default.help().version(!1),s=async e=>{try{if(n.exists()){const e=n.load();console.log(r.default({name:"CHAOS",font:"3D-ASCII",lineChars:15,padding:5,margin:2}).emptyLine().left("ipfs: "+e.ipfs).left("ethereum: "+e.ethereum).left("mnemonic: "+e.mnemonic).left("address: "+e.address).left("devices: "+e.devices).emptyLine().wrap("Have fun burning bills!").render());await a.Machine.launch(e)}else console.log("You need to configure your chaos machine before you the daemon."),console.log("Run: chaos config")}catch(e){console.log("[error] "+e.message)}};exports.daemon={command:"daemon",desc:"Launch the Chaos Machine daemon",builder:t,handler:s};
},{"../../lib/config":"0Kt0"}],"IugF":[function(require,module,exports) {
"use strict";function e(e){for(var r in e)exports.hasOwnProperty(r)||(exports[r]=e[r])}Object.defineProperty(exports,"__esModule",{value:!0}),e(require("./config")),e(require("./daemon"));
},{"./config":"OE6f","./daemon":"jTSK"}],"7QCb":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}},r=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var r={};if(null!=e)for(var t in e)Object.hasOwnProperty.call(e,t)&&(r[t]=e[t]);return r.default=e,r};Object.defineProperty(exports,"__esModule",{value:!0});const t=e(require("yargs")),a=r(require("./commands")),o=t.default.usage("chaos <command>").command(a.config).command(a.daemon).demandCommand(1,"No command provided").strict().help().alias("h","help").argv;
},{"./commands":"IugF"}]},{},["7QCb"], null)
//# sourceMappingURL=/chaos.map