#!/usr/bin/env node
parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"0Kt0":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const t=e(require("fs")),r=e(require("jsonfile")),s=e(require("os")),i=e(require("path"));exports.dir=i.default.join(s.default.homedir(),".chaos"),exports.path=i.default.join(exports.dir,"config.json"),exports.init=(()=>{t.default.existsSync(exports.dir)||t.default.mkdirSync(exports.dir),exports.save({})}),exports.exists=(()=>t.default.existsSync(exports.dir)&&t.default.existsSync(exports.path)),exports.save=(e=>r.default.writeFileSync(exports.path,e)),exports.load=(()=>r.default.readFileSync(exports.path));
},{}],"8oQ/":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var a in e)Object.hasOwnProperty.call(e,a)&&(t[a]=e[a]);return t.default=e,t},t=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const a=require("@chaosmachine/chaos.js"),s=e(require("inquirer")),i=t(require("web3")),r=new i.default,n=new RegExp(/(?:^|\s)((https?:\/\/)?(?:localhost|[\w-]+(?:\.[\w-]+)+)(:\d+)?(\/\S*)?)/),c={ipfs:{name:"ipfs",type:"input",message:"IPFS gateway: ",default:a.Machine.defaults.ipfs,validate:async e=>!!e.match(n)||"Invalid URL"},ethereum:{name:"ethereum",type:"input",message:"Ethereum gateway: ",default:a.Machine.defaults.ethereum,validate:async e=>!!e.match(n)||"Invalid URL"},contract:{name:"contract",type:"input",message:"Contract address: ",default:a.Machine.defaults.contract,validate:async e=>!!r.isAddress(e)||"Invalid address"},devices:{name:"devices",type:"confirm",message:"Enable devices: ",default:a.Machine.defaults.devices}},u={configure:async()=>{const e=await s.prompt(c.ipfs),t=await s.prompt(c.ethereum),a=await s.prompt(c.contract),i=await s.prompt(c.devices);return Object.assign({},e,t,a,i)}};exports.default=u;
},{}],"OE6f":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}},t=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var s in e)Object.hasOwnProperty.call(e,s)&&(t[s]=e[s]);return t.default=e,t};Object.defineProperty(exports,"__esModule",{value:!0});const s=e(require("yargs")),i=t(require("../../lib/config")),r=e(require("../../ui/inquirer")),o=()=>s.default.option("ipfs",{describe:"Set IPFS gateway address",type:"string"}).option("ethereum",{describe:"Set ethereum gateway address",type:"string"}).option("contract",{describe:"Set chaos contract address",type:"string"}).option("devices",{describe:"Enable chaos machine devices",type:"boolean"}).help().version(!1),a=async e=>{try{if(i.exists()||i.init(),e.ipfs){const t=i.load();t.ipfs=e.ipfs,i.save(t)}else if(e.ethereum){const t=i.load();t.ethereum=e.ethereum,i.save(t)}else if(e.contract){const t=i.load();t.contract=e.contract,i.save(t)}else if(void 0!==e.devices){const t=i.load();t.devices=e.devices,i.save(t)}else{const e=await r.default.configure();i.save(e)}}catch(e){console.log("[error] "+e.message)}};exports.config={command:"config",desc:"Configure the Chaos Machine",builder:o,handler:a};
},{"../../lib/config":"0Kt0","../../ui/inquirer":"8oQ/"}],"jTSK":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}},o=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var o={};if(null!=e)for(var r in e)Object.hasOwnProperty.call(e,r)&&(o[r]=e[r]);return o.default=e,o};Object.defineProperty(exports,"__esModule",{value:!0});const r=require("@chaosmachine/chaos.js"),t=e(require("asciiart-logo")),n=e(require("yargs")),a=o(require("../../lib/config")),i=()=>n.default.help().version(!1),s=async e=>{try{if(a.exists()){const e=a.load();console.log(t.default({font:"3D-ASCII",lineChars:15,margin:2,name:"CHAOS",padding:5}).emptyLine().left("ipfs: "+e.ipfs).left("ethereum: "+e.ethereum).left("contract: "+e.contract).left("devices: "+e.devices).emptyLine().wrap("Have fun burning bills!").render());const o=new r.Machine(e);await o.start()}else console.log("You need to configure your chaos machine before you the daemon."),console.log("Run: chaos config")}catch(e){console.log("[error] "+e.message)}};exports.daemon={command:"daemon",desc:"Launch the Chaos Machine daemon",builder:i,handler:s};
},{"../../lib/config":"0Kt0"}],"IugF":[function(require,module,exports) {
"use strict";function e(e){for(var r in e)exports.hasOwnProperty(r)||(exports[r]=e[r])}Object.defineProperty(exports,"__esModule",{value:!0}),e(require("./config")),e(require("./daemon"));
},{"./config":"OE6f","./daemon":"jTSK"}],"7QCb":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}},r=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var r={};if(null!=e)for(var t in e)Object.hasOwnProperty.call(e,t)&&(r[t]=e[t]);return r.default=e,r};Object.defineProperty(exports,"__esModule",{value:!0});const t=e(require("yargs")),a=r(require("./commands")),o=t.default.usage("chaos <command>").command(a.config).command(a.daemon).demandCommand(1,"No command provided").strict().help().alias("h","help").argv;
},{"./commands":"IugF"}]},{},["7QCb"], null)
//# sourceMappingURL=/chaos.map